name: Hello World Workflow

on:
  push:
    branches:
      - master  # or 'main', depending on your default branch

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, World!"

